"""empty message

Revision ID: d01bc11e2c19
Revises: c321030c698c
Create Date: 2024-09-29 12:27:12.271783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01bc11e2c19'
down_revision = 'c321030c698c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('merchant_company_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('company_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('merchant_company_email_key', ['company_email'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
